apiVersion: v1
kind: Secret
metadata:
  name: taskdo-secrets
  namespace: taskdo
type: Opaque
data:
  JWT_ACCESS_SECRET: <base64>
  JWT_REFRESH_SECRET: <base64>
  GOOGLE_CLIENT_SECRET: <base64>
  ENCRYPTION_KEY: <base64>
