apiVersion: v1
kind: ConfigMap
metadata:
  name: taskdo-config
  namespace: taskdo
data:
  NODE_ENV: "production"
  PORT: "3001"
  MONGO_URI: "mongodb://mongo-service:27017/taskdo"
  REDIS_URL: "redis://redis-service:6379"
  COOKIE_SECURE: "false"
  FRONTEND_URL: "http://taskdo.local"
  GOOGLE_REDIRECT_URI: "http://taskdo.local/api/auth/google/callback"
  GOOGLE_CALLBACK_URL: "http://taskdo.local/api/auth/google/callback"
  STRIPE_MONTHLY_PRICE_ID: "price_1TJu5PCPVGWl48dJpIXAg0BE"
  STRIPE_YEARLY_PRICE_ID: "price_1TJu7WCPVGWl48dJyU9Ir2DT"
